"""Init

Revision ID: 181f28b75c0b
Revises: ac5041baf63d
Create Date: 2024-05-17 11:39:07.548131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '181f28b75c0b'
down_revision: Union[str, None] = 'ac5041baf63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=13),
               existing_nullable=False)
    op.alter_column('contacts', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.String(length=13),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
